### ISSUE TITLE
Rails 6 Release

### ISSUE THREAD

**Issue by jeffnappi** [plataformatec/has_scope#110]
Looks like tests are passing with Rails 6 on Travis CI and the `has_scope.gemspec` has been updated in `master`.

Are there plans to push up a new release?

**Comment by tegon** [comment]
It should work with version `0.7.2`. Are you having any issues with it?

**Comment by jeffnappi** [comment]
Hi @tegon - it appears it should be good. Would be nice to see a release noting official Rails 6 support in the README however :)

**Comment by tegon** [comment]
I didn't see this wasn't in the changelog, we'll take a look at it. Thanks for the feedback!
