### ISSUE TITLE
apply_scopes on multiple resources

### ISSUE THREAD

**Issue by phlegx** [plataformatec/has_scope#64]
Hi!

I have an index view of ```accounts``` on ```AccountsController```. My view shows two tables. One table shows the user list (subclass of ```Account```) and a second one shows the student list (subclass of ```Account```). Every table has an own search scope:

```ruby
class AccountsController < ApplicationController

  has_scope :u_search,  :s_search, only: :index

  def index
    @users = apply_scopes(User).all
    @students = apply_scopes(Student).all
  end
...
```

On every subclass model I have implemented the scope:

```ruby
class User < Account
  scope :u_search, -> search { ... }
end

class Student < Account
  scope :s_search, -> search { ... }
end
```

**Problem**

If parameter ```u_search``` is present, the scope is applied also on ```Student```. But ```u_search``` scope don't exists on model ```Student```. How can I remove or add scopes to ```apply_scopes``` related to the model? Any idea?

**Idea**

One possible solution can be a ```if: :scope_exists?```.

```ruby
class AccountsController < ApplicationController

  has_scope :u_search,  :s_search, only: :index, if: :scope_exists?
```

**Solved**

See following patch or pull request! The simplest way is that ```apply_scopes``` ignores non existing scopes in the target (accounts). E.g. scope ```u_search``` (user search) applied on students (scope ```u_search``` is not defined in students) is ignored. Same thing with ```s_search``` (satellite search) applied on users (scope ```s_search``` is not defined in users) is ignored.

**Comment by leoplct** [comment]
+1 I have the same problem. Is it been fixed ?

**Comment by wrystr** [comment]
I did an ugly hack like this:

```
has_scope :u_search do |controller, scope, value|
  scope.class.to_s == 'User::ActiveRecord_Relation' ? scope.u_search : scope
end
```

Not fully tested obviously, work on my case.
