### ISSUE TITLE
Release stable 0.6.0

### ISSUE THREAD

**Issue by betelgeuse** [plataformatec/has_scope#67]
The current release version of inherited_resources pulls in 0.6.0.rc . It's about time to make an official 0.6.0 release?

**Comment by carlosantoniodasilva** [comment]
I think so, I'll check what we can do. Thanks.

**Comment by CyborgMaster** [comment]
Any updates on a release?

I've got the same issue here.  Seems like 0.6.0 is pretty stable, its been out for about 9 months.  I currently need a version specifier in my gemfile to get 0.6.0rc so inherited_resources isn't downgraded and would love to get rid of it as soon as you guys are ready for an official 0.6.0.

**Comment by carlosantoniodasilva** [comment]
Done, please let us know if you find any issue. Thanks.

**Comment by CyborgMaster** [comment]
Just updated my gemfile and removed the force `has_scope` version.  Everything works great.  Thanks!

**Comment by carlosantoniodasilva** [comment]
Awesome, thanks for reporting back.

On Tue, Feb 17, 2015 at 12:50 AM, CyborgMaster <notifications@github.com>
wrote:

> Just updated my gemfile and removed the force has_scope version.
> Everything works great. Thanks!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/plataformatec/has_scope/issues/67#issuecomment-74609585>
> .
>



-- 
At.
Carlos Antonio
