### ISSUE TITLE
Scope param required when applying ActiveRecord order

### ISSUE THREAD

**Issue by eduncan26** [plataformatec/has_scope#68]
When applying a scope to order data in a view you are required to use a param in the scope. This seems a little weird to me because it doesn't appear that the param is actually being used by the scope. Maybe I am missing something, but I found this behavior to be a little strange.

Here is an example of what I am doing:

**Link model**
```ruby 
class Link < ActiveRecord::Base
  scope :abc, -> title { order(:title => :asc) }
  scope :cba, -> title { order(:title => :desc) }
end
```

**Links controller**
```ruby
class LinksController < ApplicationController
  has_scope :abc
  has_scope :cba
  def index
    @links = apply_scopes(Link).all
  end
end
```

**View**
```erb
<div id="links-wrapper">
  <% @links.each do |link| %>
    <div class="link">
      <a class="link-title" href="<%= link.url %>" target="_blank"><%= link.title %></a>
      <div class="link-printed-url"><%= link.url %></div>
      <p class="link-description"><%= link.description %></p>
    </div>
  <% end %>

  <div class="link-tags">
    <%= link_to 'Order ASC', root_path(:abc => true) %>
    <%= link_to 'Order DESC', root_path(:cba => true) %>
  </div>
</div>
```

**Routes**
```ruby
Rails.application.routes.draw do
  root 'links#index'
end
```

As you can see I did pass the title param to the scope, but I am not sure why it is necessary. Maybe it is my lack of understanding with the ActiveRecord ordering, but I would have expected this use case to act similarly to the examples using the ActiveRecord where.

**Comment by carlosantoniodasilva** [comment]
I think you're looking for the [boolean type](https://github.com/plataformatec/has_scope#boolean-usage), so that you don't need the scope argument. Let me know if that solves your issue, so we can close. Thanks.

**Comment by eduncan26** [comment]
Yeah, that solves it. I was just revisiting the documentation for the where example, and noticed I missed that.

**Comment by carlosantoniodasilva** [comment]
Great :+1:
