### ISSUE TITLE
has_scope only works when I change the order of the scopes in the controller

### ISSUE THREAD

**Issue by codecalypso** [plataformatec/has_scope#69]
I'm not sure if this is a bug or if this is how its meant to function. If the order of the scopes are not changed in the controller, the gem does not function properly.

**Comment by carlosantoniodasilva** [comment]
Please give us some code examples or build an example app that shows the issue, otherwise it's impossible to figure out what might be going on. Thanks.

**Comment by codecalypso** [comment]
Okay will do. Thanks.
