### ISSUE TITLE
Has any thought been given to making this available outside of controllers?

### ISSUE THREAD

**Issue by mikesnare** [plataformatec/has_scope#70]
Love the gem, and I've used it in several projects now.  From time to time, though, I find myself wishing that this functionality were accessible outside the context of a running controller action.

Imagine a case where a job needs to be enqueued to process some matching objects based on the params.  For now, I either need to dummy up a controller to be used by my job, set the params manually, and call apply_scopes in that job, or I need to translate the result of apply_scopes in my controller to a list of IDs and pass those to my job.

Setting aside the perfectly reasonable argument that the result of apply_scopes may differ between request-time and the time at which the job is processed, it seems reasonable to want to extract the has_scopes-relevant params from the controller, pass them elsewhere, and have them be evaluated at a later time.

Is this available somewhere that I'm just unaware of?  Would this be considered a useful addition?

**Comment by carlosantoniodasilva** [comment]
If I got you right, you should be able to use has scope in a non controller environment without problems, by passing in the params hash you want to apply with the scopes like this:

```ruby
apply_scopes(Class, param: 'foo', other_param: 'bar')
```

`apply_scopes` just happen to default that hash to the `params` hash available within the controller (and that's all it should need by default). You can see [we have some tests that use has scope in a normal Ruby class](https://github.com/plataformatec/has_scope/blob/df1fb68e437ea7df7499d6f73d9568b6d09c8e50/test/has_scope_test.rb#L338-356). If there is anything that does not work outside of a controller, I'd be glad to accept a pull request fixing it (for example I just noticed we [rely on `action_name` for the `only/except` options](https://github.com/plataformatec/has_scope/blob/df1fb68e437ea7df7499d6f73d9568b6d09c8e50/lib/has_scope.rb#L171-179), so it'd be necessary to implement them in class using has scope with those options - which might make sense, but we could make it not a hard requirement or something).

Does that answer your issue?

**Comment by mikesnare** [comment]
That's actually perfect.  ``:unless``/``:only`` are such standard options for controller methods that it seems perfectly reasonable to leave them as-is, and for me to make use of the ``:if`` option where necessary.  Since the ``controller`` param passed to the block is really just whatever ``self`` was when ``apply_scopes`` was called I think I have everything I need.

Thanks!

**Comment by carlosantoniodasilva** [comment]
Awesome, please let us know if you find any issues. :)
