### ISSUE TITLE
undefined method `user_signed_in?'

### ISSUE THREAD

**Issue by atitan** [plataformatec/has_scope#74]
Hello,

I'm using has_scope for search form, and there's some customized filtering that requires user to logged in.
So I added 'user_signed_in?' provided by devise to has_scope's if condition.

Then I got "ActionController::RoutingError" saying "undefined method `user_signed_in?' for CoursesController:Class". The exception was thrown inside the ActionDispatch::Routing::RouteSet::Dispatcher.

Is there any workaround to solve this?

```
has_scope :hide_passed_courses, type: :boolean, if: user_signed_in? do |controller, scope|
  scope.hide_passed_courses(controller.current_user.passed_courses)
end
```

**Comment by josevalim** [comment]
Arguments given to :if must be a symbol:

```ruby
has_scope :hide_passed_courses, type: :boolean, if: :user_signed_in? do |controller, scope|
  scope.hide_passed_courses(controller.current_user.passed_courses)
end
```

**Comment by atitan** [comment]
Thanks, you saved my day. :)
