### ISSUE TITLE
apply_scopes available in helpers or views?

### ISSUE THREAD

**Issue by ausminternet** [plataformatec/has_scope#75]
Hey there,

Is there any possibility to use ```apply_scopes``` in a helper or a view?

**Comment by carlosantoniodasilva** [comment]
You could just add `helper_method :apply_scopes` to the controller you want (or application controller), although I'd not recommend doing it as it seems a bit dirty - keep in mind I'm out of context anyway. ;)

**Comment by ausminternet** [comment]
You're right and after thinking about it, I found a solution to implement it in my controller. (What leads me to another problem: https://github.com/plataformatec/has_scope/issues/72)
