### ISSUE TITLE
Push 0.7.0 tag to GitHub

### ISSUE THREAD

**Issue by kaspth** [plataformatec/has_scope#85]
@lucasmazza I think this was forgotten when releasing 0.7.0. It shows up fine on RubyGems: https://rubygems.org/gems/has_scope

Thanks for the Rails 5 support! ❤️

**Comment by lucasmazza** [comment]
@kaspth https://github.com/plataformatec/has_scope/releases/tag/v0.7.0 ❤️

**Comment by kaspth** [comment]
Thanks!
