### ISSUE TITLE
Scope named 'exit' calls SystemExit

### ISSUE THREAD

**Issue by JonaC22** [plataformatec/has_scope#87]
I have a model called `Movement ` configured with two scopes: **entrance** and **exit**.

When I filter by **entrance** everything works as expected, but with **exit**, Rails finishes the request executing the exit method (SystemExit)

Is this behaviour expected? Should I rename my scope? :confused:

Thanks

**Comment by georgeguimaraes** [comment]
I've just created a scope `exit` and used `/exit=true` to make the controller call the scope.
Everything seems to be working fine.

 Can you please provide a sample application that reproduces the error?
